// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt9230iy4peiQRL9zNJ5rO70J88m4lq8Q',
    appId: '1:443484449237:web:f86ed41a48d788bc44355c',
    messagingSenderId: '443484449237',
    projectId: 'flushpoint-aa8d2',
    authDomain: 'flushpoint-aa8d2.firebaseapp.com',
    storageBucket: 'flushpoint-aa8d2.firebasestorage.app',
    measurementId: 'G-PP9L8P7HJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwRk2QMnfWRIwUORYeRnzlrE6JJ8ajaNk',
    appId: '1:443484449237:android:f636a9de31ec73fe44355c',
    messagingSenderId: '443484449237',
    projectId: 'flushpoint-aa8d2',
    storageBucket: 'flushpoint-aa8d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ1DqNQ9E8xuYRpIw_1RuDhHs4VcGPtD4',
    appId: '1:443484449237:ios:117574230c3501f644355c',
    messagingSenderId: '443484449237',
    projectId: 'flushpoint-aa8d2',
    storageBucket: 'flushpoint-aa8d2.firebasestorage.app',
    iosBundleId: 'com.example.flutterSetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ1DqNQ9E8xuYRpIw_1RuDhHs4VcGPtD4',
    appId: '1:443484449237:ios:117574230c3501f644355c',
    messagingSenderId: '443484449237',
    projectId: 'flushpoint-aa8d2',
    storageBucket: 'flushpoint-aa8d2.firebasestorage.app',
    iosBundleId: 'com.example.flutterSetup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt9230iy4peiQRL9zNJ5rO70J88m4lq8Q',
    appId: '1:443484449237:web:d05519652b61c68944355c',
    messagingSenderId: '443484449237',
    projectId: 'flushpoint-aa8d2',
    authDomain: 'flushpoint-aa8d2.firebaseapp.com',
    storageBucket: 'flushpoint-aa8d2.firebasestorage.app',
    measurementId: 'G-KWGQ581F31',
  );
}
